import { expect, test, type Page } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'

const slugs = ['folio', 'atlas', 'monograph', 'workbench', 'index', 'gallery', 'timeline', 'dialogue', 'fieldnotes', 'quiet']

async function expectAccessible(page: Page, selector: string) {
  const results = await new AxeBuilder({ page }).include(selector).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()
  expect(results.violations.map(({ id, nodes }) => ({
    id,
    nodes: nodes.map(({ target, failureSummary }) => ({ target, failureSummary })),
  }))).toEqual([])
}

for (const slug of slugs) {
  test(`${slug}: readable, accessible, responsive academic profile`, async ({ page }) => {
    const errors: string[] = []
    page.on('pageerror', (error) => errors.push(error.message))
    await page.goto(`/designs/${slug}`)
    const surface = page.locator(`.design-surface.${slug}`)
    await expect(surface).toBeVisible()
    await page.evaluate(() => document.fonts.ready)
    await expect(surface).toContainText('Zekun')
    await expect(surface).toContainText(/Georgia/)
    const profileMenu = surface.getByRole('button', { name: 'About & links' })
    const menuNeeded = slug === 'index' && await profileMenu.isVisible()
    if (menuNeeded) await profileMenu.click()
    await expect(surface.locator('a[href="/cv.pdf"]:visible').first()).toBeVisible()
    await expect(surface.locator('a[href="mailto:zekun@gatech.edu"]:visible').first()).toBeVisible()
    if (menuNeeded) await profileMenu.click()
    const overflow = await surface.evaluate((element) => ({
      scroll: element.scrollWidth,
      available: document.documentElement.clientWidth,
    }))
    expect(overflow.scroll, 'The design should fit the viewport without clipped horizontal content').toBeLessThanOrEqual(overflow.available + 1)
    expect(errors, 'The page should have no runtime errors').toEqual([])
    const results = await new AxeBuilder({ page })
      .include('.design-surface')
      .withTags(['wcag2a', 'wcag2aa', 'wcag21aa'])
      .analyze()
    expect(results.violations.map((violation) => ({
      id: violation.id,
      help: violation.help,
      nodes: violation.nodes.map((node) => ({ target: node.target, summary: node.failureSummary })),
    }))).toEqual([])
  })
}

test('the chooser opens all ten designs and remembers favorites', async ({ page }) => {
  await page.goto('/designs')
  await expect(page.locator('.studio-design-card')).toHaveCount(10)
  const accessibility = await new AxeBuilder({ page }).include('.studio').withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()
  expect(accessibility.violations.map(({ id, nodes }) => ({ id, targets: nodes.map(({ target }) => target) }))).toEqual([])
  await page.getByRole('button', { name: '收藏 Folio', exact: true }).click()
  await page.reload()
  await expect(page.getByRole('button', { name: '取消收藏 Folio', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: /已收藏/ }).click()
  await expect(page.locator('.studio-design-card')).toHaveCount(1)
  await page.getByRole('link', { name: '进入 Folio · 学术刊物', exact: true }).click()
  await expect(page.locator('.design-surface.folio')).toBeVisible()
  await page.getByLabel('选择设计方案', { exact: true }).selectOption('atlas')
  await expect(page.locator('.design-surface.atlas')).toBeVisible()
  await page.getByRole('link', { name: '返回全部 10 个方案' }).click()
  await expect(page.locator('.studio-design-card')).toHaveCount(10)
})

test('comparison uses working independent pages at desktop and phone sizes', async ({ page }) => {
  await page.goto('/designs/compare?left=folio&right=atlas')
  await expect(page.frameLocator('iframe[title="Folio 桌面预览"]').locator('.design-surface.folio')).toBeVisible()
  await expect(page.frameLocator('iframe[title="Atlas 桌面预览"]').locator('.design-surface.atlas')).toBeVisible()
  await page.getByRole('button', { name: '手机', exact: true }).click()
  const phone = page.frameLocator('iframe[title="Folio 手机预览"]')
  await expect(phone.locator('.design-surface.folio')).toBeVisible()
  await expect(phone.locator('.studio-review-controls')).toHaveCount(0)
  expect(await phone.locator('html').evaluate((element) => element.clientWidth)).toBe(390)
  await page.getByLabel('右侧方案', { exact: true }).selectOption('quiet')
  await expect(page.frameLocator('iframe[title="Still / Lens / Black 手机预览"]').locator('.design-surface.quiet')).toBeVisible()
})

test('Folio supports focused reading, keyboard return, and the complete archive', async ({ page }) => {
  await page.goto('/designs/folio')
  const trigger = page.locator('.folio-recent button').first()
  await trigger.click()
  const reader = page.getByRole('dialog')
  await expect(reader).toBeVisible()
  await expect(reader.getByRole('button', { name: 'Close', exact: true })).toBeFocused()
  await expectAccessible(page, '.folio-reader')
  await page.keyboard.press('Escape')
  await expect(reader).not.toBeVisible()
  await expect(trigger).toBeFocused()
  await page.getByRole('button', { name: /Unfold the full archive/ }).click()
  await expect(page.locator('.folio-archive-entry')).toHaveCount(15)
  await page.getByRole('searchbox', { name: 'Search papers by title, author, or keyword' }).fill('rAnK-1 FiShEr')
  await expect(page.locator('.folio-archive-entry')).toHaveCount(1)
  await page.locator('.folio-entry-heading').click()
  await expect(page.locator('.folio-archive-entry a[href="https://arxiv.org/abs/2509.23593"]')).toBeVisible()
  await page.getByRole('searchbox').fill('zzznomatchingpublication')
  await expect(page.locator('.folio-archive-entry')).toHaveCount(0)
  await page.getByRole('button', { name: 'Clear all filters', exact: true }).click()
  await expect(page.locator('.folio-archive-entry')).toHaveCount(15)
})

test('Atlas keeps map, list, and paper inspector in sync', async ({ page }) => {
  await page.goto('/designs/atlas')
  await page.locator('.atlas-map-topic').filter({ hasText: 'compositionality' }).click()
  await expect(page.locator('.atlas-result')).toHaveCount(1)
  await expect(page.locator('#atlas-inspector-title')).toContainText('Test-Time Compositional Generalization')
  await page.getByRole('button', { name: /List(?: view)?$/, exact: false }).click()
  await expect(page.locator('.atlas-map-region')).toHaveCount(0)
  await expect(page.locator('.atlas-result')).toHaveCount(1)
  await page.getByRole('button', { name: 'All topics', exact: true }).click()
  await expect(page.locator('.atlas-result')).toHaveCount(15)
  await page.locator('.atlas-result-title').last().click()
  await expect(page.locator('#atlas-inspector-title')).toContainText('Foundations for NLP-assisted')
  await expect(page.locator('.atlas-read-paper')).toHaveAttribute('href', 'https://arxiv.org/abs/2205.02829')
})

test('Monograph chapters and bibliography work with deep links and empty results', async ({ page }) => {
  await page.goto('/designs/monograph')
  await page.getByRole('link', { name: /Open the bibliography/ }).click()
  await expect(page).toHaveURL(/#monograph-bibliography$/)
  await expect(page.locator('.monograph-bibliography-entry')).toHaveCount(15)
  await page.getByRole('searchbox', { name: 'Find a paper' }).fill('rank-1 fisher')
  await expect(page.locator('.monograph-bibliography-entry')).toHaveCount(1)
  await page.getByLabel('Year', { exact: true }).selectOption('2022')
  await expect(page.getByRole('heading', { name: 'No papers match this search.' })).toBeVisible()
  await page.getByRole('button', { name: 'Show all 15 papers' }).click()
  await expect(page.locator('.monograph-bibliography-entry')).toHaveCount(15)
  await page.reload()
  await expect(page.locator('.monograph-bibliography-entry')).toHaveCount(15)
  await expectAccessible(page, '.design-surface.monograph')
})

test('Workbench lets a reader build, compose, reset, and find related research', async ({ page }) => {
  await page.goto('/designs/workbench')
  await page.getByRole('button', { name: 'Add observation', exact: true }).click()
  await expect(page.locator('#workbench-feedback')).toContainText('Coral square added')
  await expect(page.getByRole('button', { name: 'Already in the tree', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Compose', exact: true }).click()
  await page.getByRole('button', { name: 'Compose concepts', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Concept composed', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Reset', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Add observation', exact: true })).toBeEnabled()
  await page.getByRole('searchbox', { name: 'Find a paper', exact: true }).fill('rank-1 fisher')
  await expect(page.locator('.workbench-archive-item')).toHaveCount(1)
  await page.getByRole('button', { name: 'Clear filters', exact: true }).click()
  await expect(page.locator('.workbench-archive-item')).toHaveCount(15)
})

test('Index supports keyboard reading and preserves a useful path back to search', async ({ page }) => {
  await page.goto('/designs/index')
  const search = page.getByRole('searchbox', { name: 'Search title, author, topic, or year', exact: true })
  await search.fill('rank-1 fisher')
  await expect(page.locator('.index-paper-button')).toHaveCount(1)
  const record = page.locator('.index-paper-button').first()
  await record.focus()
  await page.keyboard.press('Enter')
  await expect(page.locator('#index-paper-title')).toBeVisible()
  await expect(page.locator('#index-paper-title')).toContainText('Avoid Catastrophic Forgetting')
  await expect(page.locator('#index-paper-title')).toBeFocused()
  await expectAccessible(page, '.index-reader')
  await page.keyboard.press('Escape')
  await expect(record).toBeFocused()
  await search.fill('zzznomatchingpublication')
  await expect(page.getByRole('heading', { name: 'No matching papers.' })).toBeVisible()
  await page.getByRole('button', { name: 'Reset the index', exact: true }).click()
  await expect(page.locator('.index-paper-button')).toHaveCount(15)
  await expect(search).toBeFocused()
})

test('Gallery changes exhibits and makes the complete collection discoverable', async ({ page }) => {
  await page.goto('/designs/gallery')
  await page.getByRole('button', { name: 'Next exhibit', exact: true }).click()
  await expect(page.getByRole('tab', { name: /Memory & retention/ })).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByRole('heading', { name: 'Room for the next idea.' })).toBeVisible()
  await page.getByRole('button', { name: 'Previous exhibit', exact: true }).click()
  await expect(page.getByRole('tab', { name: /Concept hierarchies/ })).toHaveAttribute('aria-selected', 'true')
  await page.getByRole('searchbox', { name: 'Search the collection', exact: true }).fill('rank-1 fisher')
  await expect(page.locator('.gallery-collection-item')).toHaveCount(1)
  await page.locator('.gallery-paper-row').click()
  await expect(page.locator('.gallery-collection-item a[href="https://arxiv.org/abs/2509.23593"]')).toBeVisible()
  await page.getByLabel('Year', { exact: true }).selectOption('2022')
  await expect(page.getByRole('heading', { name: 'No papers match these filters.' })).toBeVisible()
  await page.getByRole('button', { name: 'Show all 15 publications' }).click()
  await expect(page.locator('.gallery-collection-item')).toHaveCount(15)
})

test('Continuum traces actual publication years and meaningful topic lenses', async ({ page }) => {
  await page.goto('/designs/timeline')
  await expect(page.locator('.timeline-paper')).toHaveCount(15)
  await page.getByRole('button', { name: /^compositionality/ }).click()
  await expect(page.locator('.timeline-paper')).toHaveCount(1)
  await expect(page.locator('.timeline-paper')).toContainText('Test-Time Compositional Generalization')
  await expect(page.locator('.timeline-year-nav a')).toHaveCount(1)
  await page.getByRole('link', { name: '2026, 1 paper', exact: true }).click()
  await expect(page).toHaveURL(/#timeline-year-2026$/)
  await page.getByRole('button', { name: /^All work/ }).click()
  await expect(page.locator('.timeline-paper')).toHaveCount(15)
  await page.locator('.timeline-paper-details summary').first().click()
  await expect(page.locator('.timeline-paper-expanded').first()).toBeVisible()
  await expectAccessible(page, '.design-surface.timeline')
})

test('Dialogue provides authored reading paths and a direct route to every paper', async ({ page }) => {
  await page.goto('/designs/dialogue')
  const questions = page.getByRole('navigation', { name: 'Choose a question', exact: true })
  await questions.getByRole('button', { name: 'How can AI keep learning?', exact: true }).click()
  await expect(page.locator('#dialogue-response-title')).toBeFocused()
  await expect(page.locator('#dialogue-response-title')).toContainText('New skills.')
  await expect(page.locator('.dialogue-paper-trail > li')).toHaveCount(3)
  await page.getByRole('button', { name: /^All publications/ }).click()
  await expect(page.locator('.dialogue-publication-list > li')).toHaveCount(15)
  await page.getByRole('searchbox', { name: 'Search the collection' }).fill('rank-1 fisher')
  await expect(page.locator('.dialogue-publication-list > li')).toHaveCount(1)
  await page.getByLabel('Year', { exact: true }).selectOption('2022')
  await expect(page.getByRole('heading', { name: 'No papers found for that combination.' })).toBeVisible()
  await page.getByRole('button', { name: 'Show all 15 papers' }).click()
  await expect(page.locator('.dialogue-publication-list > li')).toHaveCount(15)
  await expectAccessible(page, '.design-surface.dialogue')
  await questions.getByRole('button', { name: 'Can we get in touch?', exact: true }).click()
  await expect(page.locator('.dialogue-contact-email')).toHaveAttribute('href', 'mailto:zekun@gatech.edu')
})

test('Fieldnotes connects each annotation to its source and exposes the full bibliography', async ({ page }) => {
  await page.goto('/designs/fieldnotes')
  await page.getByRole('tab', { name: /Compositional concepts/ }).click()
  const panel = page.getByRole('tabpanel', { name: /Compositional concepts/ })
  await expect(panel).toBeVisible()
  await panel.getByRole('button', { name: /Compose$/ }).click()
  await expect(panel.getByRole('heading', { name: 'Combine concepts through a shared score.' })).toBeVisible()
  await expect(panel.locator('.fieldnotes-source-link')).toHaveAttribute('href', 'https://arxiv.org/abs/2605.07078')
  await page.getByRole('button', { name: 'Browse all 15 papers', exact: true }).click()
  await expect(page.locator('.fieldnotes-bibliography-list > details')).toHaveCount(15)
  await page.getByRole('searchbox', { name: 'Find a paper', exact: true }).fill('rank-1 fisher')
  await expect(page.locator('.fieldnotes-bibliography-list > details')).toHaveCount(1)
  await page.locator('#fieldnotes-topic').selectOption('reinforcement learning')
  await expect(page.getByText('No papers match this selection.', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Clear search and filters', exact: true }).click()
  await expect(page.locator('.fieldnotes-bibliography-list > details')).toHaveCount(15)
  await expectAccessible(page, '.design-surface.fieldnotes')
})

test('Still keeps introduction, contact, and focused reading easy to move between', async ({ page }) => {
  await page.goto('/designs/quiet')
  const contact = page.getByRole('button', { name: 'Contact', exact: true })
  await contact.click()
  const dialog = page.getByRole('dialog')
  await expect(dialog).toBeVisible()
  await expect(dialog.getByRole('heading', { name: 'Let’s talk.' })).toBeVisible()
  await expectAccessible(page, '.quiet-info-dialog')
  await page.keyboard.press('Escape')
  await expect(dialog).not.toBeVisible()
  await expect(contact).toBeFocused()
  const trigger = page.locator('.quiet-nav-publications:visible')
  await trigger.click()
  await expect(page.locator('#quiet-reader-title')).toBeFocused()
  await expect(page.locator('.quiet-paper')).toHaveCount(15)
  await page.getByRole('searchbox', { name: 'Search publications', exact: true }).fill('rank-1 fisher')
  await expect(page.locator('.quiet-paper')).toHaveCount(1)
  await page.locator('.quiet-paper-details summary').click()
  await expect(page.locator('.quiet-paper a[href="https://arxiv.org/abs/2509.23593"]')).toBeVisible()
  await expectAccessible(page, '.design-surface.quiet')
  await page.getByRole('searchbox').fill('zzznomatchingpublication')
  await page.getByRole('button', { name: 'Show all 15 papers' }).click()
  await expect(page.locator('.quiet-paper')).toHaveCount(15)
  await page.getByRole('button', { name: 'Back to introduction', exact: true }).first().click()
  await expect(page.locator('.quiet-home')).toBeVisible()
  await expect(trigger).toBeFocused()
})
