// Transcribed from the author-supplied NeurIPS PDF, Section 3.3, Eqs. 5–13.
// Keep this module independent of React so the static article uses the same math.
const paper = '/papers/trust-region-continual-learning.pdf?v=f24a30d7db6c'

export const metaLearningConnection = {
  title: 'The meta-learning structure inside Trust Region',
  introduction: 'Compare the contribution of one earlier task. The current-task gradient remains in the training update. Here δᵢ = θ − θᵢ* measures displacement from the earlier checkpoint.',
  steps: [
    {
      id: 'updates',
      label: 'The two updates',
      title: 'Start with the old-task gradients',
      text: 'Trust Region combines replay with a Fisher penalty. MAML first adapts on support data, then differentiates the query loss through that step.',
      sharedTex: String.raw`\theta_i'=\theta-\alpha\,g_i^{\mathrm{s}}(\theta)`,
      sharedLabel: 'MAML takes one support-data gradient step with step size alpha.',
      trustTex: String.raw`g_i^{\mathrm{TR}}=\beta\,\widetilde g_i+\lambda F_i\delta_i`,
      trustLabel: 'The Trust Region old-task gradient is beta times the replay gradient plus lambda times Fisher times the displacement.',
      mamlTex: String.raw`g_i^{\mathrm{MAML}}=(I-\alpha H_i^{\mathrm{s}})\,g_i^{\mathrm{q}}(\theta_i')`,
      mamlLabel: 'The MAML meta-gradient is identity minus alpha times the support Hessian, multiplied by the query gradient at the adapted parameters.',
      source: `${paper}#page=5`,
      sourceLabel: 'Eqs. 5–6',
    },
    {
      id: 'locality',
      label: 'Stay local',
      title: 'Replay supplies the query signal. Fisher supplies curvature.',
      text: 'Near an earlier optimum, the paper approximates the replay and adapted-query gradients by Fᵢδᵢ, and the support Hessian by Fᵢ.',
      sharedTex: String.raw`\widetilde g_i\simeq g_i^{\mathrm{q}}(\theta_i')\simeq F_i\delta_i,\qquad H_i^{\mathrm{s}}\simeq F_i`,
      sharedLabel: 'Locally, replay and adapted-query gradients are approximated by Fisher times displacement. The support Hessian is approximated by the same Fisher.',
      trustTex: String.raw`g_i^{\mathrm{TR}}\simeq(\beta+\lambda)\,F_i\delta_i`,
      trustLabel: 'Trust Region reduces to beta plus lambda, times Fisher times displacement.',
      mamlTex: String.raw`g_i^{\mathrm{MAML}}\simeq(F_i-\alpha F_i^2)\,\delta_i`,
      mamlLabel: 'The MAML meta-gradient reduces to Fisher minus alpha times Fisher squared, applied to the displacement.',
      source: `${paper}#page=6`,
      sourceLabel: 'Eqs. 7–12',
    },
    {
      id: 'rank-one',
      label: 'Use rank-1',
      title: 'Applying Fisher twice preserves its direction',
      text: 'For rank-1 Fisher, ρᵢ is the nonzero eigenvalue and uᵢ is a unit vector. The second curvature factor changes the scale, so both expressions reduce to the same Fᵢδᵢ direction.',
      sharedTex: String.raw`F_i\simeq\rho_i u_i u_i^\top\quad\Longrightarrow\quad F_i^2\simeq\rho_i F_i`,
      sharedLabel: 'Rank-1 Fisher is rho times a unit vector outer product, so Fisher squared is approximately rho times Fisher.',
      trustTex: String.raw`g_i^{\mathrm{TR}}\simeq\underbrace{(\beta+\lambda)}_{\text{scale}}\,\underbrace{F_i\delta_i}_{\text{shared direction}}`,
      trustLabel: 'Trust Region has scale beta plus lambda and shared direction Fisher times displacement.',
      mamlTex: String.raw`g_i^{\mathrm{MAML}}\simeq\underbrace{(1-\alpha\rho_i)}_{\text{scale}}\,\underbrace{F_i\delta_i}_{\text{shared direction}}`,
      mamlLabel: 'MAML has scale one minus alpha rho and the same Fisher-times-displacement direction.',
      source: `${paper}#page=6`,
      sourceLabel: 'Eqs. 11–13',
    },
  ],
  conditionTex: String.raw`1-\alpha\rho_i>0`,
  conditionLabel: 'One minus alpha rho must be positive for the per-task descent directions to agree.',
  conclusion: 'Under these local approximations and a positive MAML coefficient, both old-task contributions descend along −Fᵢδᵢ. Their scales can differ across tasks. This connects the continual-learning objective to a MAML-style initialization without adding a support/query training loop.',
  notation: [
    [String.raw`\widetilde g_i`, 'replay gradient'],
    [String.raw`g_i^{\mathrm{s}},\,g_i^{\mathrm{q}}`, 'support and query gradients'],
    [String.raw`H_i^{\mathrm{s}}`, 'support Hessian'],
    [String.raw`\beta,\,\lambda`, 'replay and Fisher weights'],
    [String.raw`\alpha`, 'MAML inner step size'],
  ],
  source: `${paper}#page=5`,
  appendix: `${paper}#page=14`,
  evidence: {
    cosine: 0.83,
    source: `${paper}#page=19`,
    label: 'CW10, Appendix D.1, Table 9',
    description: 'Mean cosine similarity between the old-task update and an exact second-order, one-step MAML meta-gradient, evaluated at the same parameters with support and query samples from the same stream.',
  },
} as const
